#! /bin/bash

# Does basic static checks on the code.
# to check compliance before a git commit: ln -s '../../pre-commit.sh' .git/hooks/pre-commit
# Requires standard js: npm install --global standard

set -e

echo checking…

standard --env mocha --env browser --globals assert tests/**.js
standard --env browser js/**
standard --env serviceworker worker.js
! grep -r 'console\.log' js/

echo all good!
